- conf/layer.conf
Signed-off-by: Robin Mugridge <robin.mugridge@oxinst.com>
> layer.conf: Add 'warrior' to layer compatibility.

- recipes-mono/libgdiplus/libgdiplus-6.0.2/0001-fix-cross-compile.patch
- recipes-mono/libgdiplus/libgdiplus_6.0.2.bb
I just published my work I did some time ago, libgdiplus 6.0.2 is not the latest version anymore. I'll see if I can update to 6.0.4 (the latest version) this week.
Edit: I just saw the pull request #23 that seems to be more major. Feel free to merge that one instead of mine.
> libgdiplus: Add support for 6.0.2

- conf/layer.conf
- recipes-mono/nuget/nuget_5.2.0.bb
Also use it as the default preferred version.
Signed-off-by: Böszörményi Zoltán <zboszor@pr.hu>
> nuget: Add recipe for version 5.2.0

- recipes-mono/libgdiplus/libgdiplus.inc
> libgdiplus: Allow building without X11

- conf/layer.conf
> conf/layer.conf: Add gatesgarth to LAYERSERIES_COMPAT

- conf/layer.conf
- recipes-mono/libgdiplus/libgdiplus-6.0.4/0001-configure-Fix-build-with-Gentoo-pango.patch
- recipes-mono/libgdiplus/libgdiplus-6.0.5/0001-configure-Fix-build-with-Gentoo-pango.patch
- recipes-mono/libgdiplus/libgdiplus-6.0.5/0001-fix-cross-compile.patch
- recipes-mono/libgdiplus/libgdiplus-native_6.0.5.bb
- recipes-mono/libgdiplus/libgdiplus_6.0.4.bb
- recipes-mono/libgdiplus/libgdiplus_6.0.5.bb
- recipes-mono/mono/mono-6.12.0.107.inc
- recipes-mono/mono/mono-6.12.0.107/0001-patch-XplatUIX11-cursor.diff
- recipes-mono/mono/mono-6.12.0.107/shm_open-test-crosscompile.diff
- recipes-mono/mono/mono-6.xx.inc
- recipes-mono/mono/mono-native_6.12.0.107.bb
- recipes-mono/mono/mono_6.12.0.107.bb
Fix build issues for libgdiplus and mono 6.10 (found, fixed and tested on Sumo)
Add libgdiplus 6.0.5
Add Mono 6.12.0.107
Prefer new versions
> Add Mono 6.12

- recipes-mono/mono/mono-6.xx.inc
Fixes #60 - maybe not the full solution but it definitely silences the quoted file-rdep QA errors.
> mono: Attempt to fix RDEPENDS

- conf/layer.conf
> Add hardknott compatibility

- recipes-mono/mono/mono-6.12.0.147.inc
- recipes-mono/mono/mono-6.12.0.147/0001-patch-XplatUIX11-cursor.diff
- recipes-mono/mono/mono-6.12.0.147/shm_open-test-crosscompile.diff
- recipes-mono/mono/mono-native_6.12.0.147.bb
- recipes-mono/mono/mono_6.12.0.147.bb
Use the tagged release from GitHub.
Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>
> mono: Add recipe for version 6.12.0.147

- recipes-mono/mono/mono-6.12.0.161.inc
- recipes-mono/mono/mono-6.12.0.161/0001-patch-XplatUIX11-cursor.diff
- recipes-mono/mono/mono-6.12.0.161/0004-Disable-DebuggerTests.Crash-since-it-fails-on-Linux-.patch
- recipes-mono/mono/mono-6.12.0.161/0007-Don-t-include-mono-dtrace.h-when-generating-offsets.patch
- recipes-mono/mono/mono-6.12.0.161/0008-2020-02-marshal-Fix-VARIANT-and-BSTR-marshaling-in-s.patch
- recipes-mono/mono/mono-6.12.0.161/0010-Fix-the-System.String.Replace-throwing-NotImplemente.patch
- recipes-mono/mono/mono-6.12.0.161/0014-2020-02-Backport-r4-conv-i-fixes-20986.patch
- recipes-mono/mono/mono-6.12.0.161/0016-arm64-Fix-wrong-marshalling-in-gsharedvt-transition-.patch
- recipes-mono/mono/mono-6.12.0.161/0019-MonoIO-Wrap-calls-to-open-in-EINTR-handling-21042.patch
- recipes-mono/mono/mono-6.12.0.161/0020-2020-02-Fix-leak-in-assembly-specific-dllmap-lookups.patch
- recipes-mono/mono/mono-6.12.0.161/0024-2020-02-Start-a-dedicated-thread-for-MERP-crash-repo.patch
- recipes-mono/mono/mono-6.12.0.161/0025-2020-02-Fix-memory-leak-during-data-registration-211.patch
- recipes-mono/mono/mono-6.12.0.161/0026-mini-Add-GC-Unsafe-transitions-in-mono_pmip-21186.patch
- recipes-mono/mono/mono-6.12.0.161/0027-Adding-null-check-to-avoid-abort-when-invalid-IL-is-.patch
- recipes-mono/mono/mono-6.12.0.161/0028-Mono.Profiler.Aot-Write-true-string-wire-length-2119.patch
- recipes-mono/mono/mono-6.12.0.161/0029-2020-02-backport-metadata-fixes-21190.patch
- recipes-mono/mono/mono-6.12.0.161/0030-2020-02-linux-Some-pseudo-tty-fixes-21205.patch
- recipes-mono/mono/mono-6.12.0.161/0031-mini-Don-t-add-unbox-tramopline-on-generic-DIM-calls.patch
- recipes-mono/mono/mono-6.12.0.161/0032-Ignore-inherit-param-for-ParameterInfo.GetCustomAttr.patch
- recipes-mono/mono/mono-6.12.0.161/0035-aot-Don-t-leak-unbox-trampolines-21225.patch
- recipes-mono/mono/mono-6.12.0.161/0036-Revert-2020-02-Start-a-dedicated-thread-for-MERP-cra.patch
- recipes-mono/mono/mono-6.12.0.161/0037-Allow-nfloat-to-be-in-the-ObjCRuntime-namespace-and-.patch
- recipes-mono/mono/mono-6.12.0.161/0039-aot-Prepend-the-assembly-name-to-the-names-of-gshare.patch
- recipes-mono/mono/mono-6.12.0.161/shm_open-test-crosscompile.diff
- recipes-mono/mono/mono-native_6.12.0.161.bb
- recipes-mono/mono/mono_6.12.0.161.bb
Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>
> mono: add 6.12.0.161

- conf/layer.conf
Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>
> mono: Default to 6.12.0.161

- recipes-mono/mono-xsp/mono-xsp_git.bb
Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>
> mono_xsp: Fix Github URI to https

- conf/layer.conf
- recipes-mono/mono/mono-4.xx.inc
- recipes-mono/mono/mono-5.xx.inc
This at least allows Yocto current master start building things with meta-mono.
More fixes may be needed.
Also, I am not really a python expert.
The python scriptlet change may be expressed in a shorter but still working way.
> Mickledore support

- recipes-python/python3-clr-loader/python3-clr-loader.bb
- recipes-python/python3-pythonnet/python3-pythonnet.bb
Try to fix recipe install issue https://github.com/DynamicDevices/meta-mono/issues/168
> Fix python3-pythonnet recipe build for langdale

- recipes-mono/dotnet/dotnet_7.0.202.bb
hello!
maybe it is time to add a new recipe :)
> dotnet: add dotnet v7.0.202

- recipes-mono/images/test-image-mono.bb
- recipes-python/python3-clr-loader/python3-clr-loader.bb
- recipes-python/python3-pythonnet/python3-pythonnet.bb
Add Python.NET recipe to kirkstone
> Add python3-clr-loader and python3-pythonnet recipe to kirkstone

- recipes-mono/images/test-image-mono.bb
- recipes-python/python3-clr-loader/python3-clr-loader.bb
- recipes-python/python3-pythonnet/python3-pythonnet.bb
Add Python.NET recipe to langdale
> Add python3-clr-loader and python3-pythonnet recipe to langdale

- recipes-mono/dotnet/dotnet_3.1.11.bb
- recipes-mono/dotnet/dotnet_6.0.407.bb
- update dotnet 6 to 6.0.15
- add msbuild replace libhostfxr fixes
> Msbuild replace libhostfxr with dotnet with fixes and update dotnet 6 to 6.0.15 in langdale

- recipes-mono/dotnet/dotnet_3.1.11.bb
- recipes-mono/dotnet/dotnet_6.0.407.bb
Fixes https://github.com/DynamicDevices/meta-mono/pull/163 in kirkstone
> Msbuild replace libhostfxr with dotnet with fixes in kirkstone

- recipes-python/python3-clr-loader/python3-clr-loader.bb
- recipes-python/python3-pythonnet/python3-pythonnet.bb
Update
- [python3-pythonnet](https://pypi.org/project/pythonnet/) 3.0.2
- [python3-clr-loader](https://pypi.org/project/clr-loader/) 0.2.6
> Update python3-pythonnet and python3-clr-loader

- recipes-python/python3-pythonnet/python3-pythonnet.bb
Update python3-pythonnet to v3.0.3
> python3-pythonnet: update to v3.0.3

- conf/layer.conf
Test build the same packages as the CI on a local poky master checkout.
> conf/layer.conf: Add scarthgap to LAYERSERIES_COMPAT

- recipes-mono/dotnet/dotnet.inc
- recipes-mono/dotnet/dotnet_6.0.423.bb
- recipes-mono/dotnet/dotnet_8.0.301.bb
Remove duplicated content and use it in `dotnet.inc`.
> dotnet: Refactor dotnet recipes

- recipes-mono/mono/mono-4.xx.inc
- recipes-mono/mono/mono-4.xx/0003-include-sys-sysmacros.h-for-makedev.patch
- recipes-mono/mono/mono-base.inc
> Backport mono fixes to Kirkstone

- recipes-mono/mono/mono-4.xx.inc
- recipes-mono/mono/mono-4.xx/0003-include-sys-sysmacros.h-for-makedev.patch
- recipes-mono/mono/mono-base.inc
> Backport mono fixes to nanbield

- recipes-mono/mono/mono-4.xx.inc
- recipes-mono/mono/mono-4.xx/0003-include-sys-sysmacros.h-for-makedev.patch
- recipes-mono/mono/mono-base.inc
> Backport mono fixes to styhead

- recipes-mono/mono/mono-4.xx.inc
- recipes-mono/mono/mono-4.xx/0003-include-sys-sysmacros.h-for-makedev.patch
- recipes-mono/mono/mono-base.inc
> Backport mono fixes to scarthgap

- recipes-python/python3-pythonnet/python3-pythonnet.bb
- python3-pythonnet Update to v3.0.4
> python3-pythonnet: Update to v3.0.4

- recipes-mono/mono/mono-6.12.0.161/0001-Add-libusb-1.0-mapping.patch
- recipes-mono/mono/mono-6.12.0.182/0001-Add-libusb-1.0-mapping.patch
- recipes-mono/mono/mono_6.12.0.161.bb
- recipes-mono/mono/mono_6.12.0.182.bb
The patch is added to versions 6.12.0.161 and 6.12.0.182.
> Add libusb mapping (nanbield)
