- conf/layer.conf
- recipes-mono/mono/mono-5.16.0.179.inc
- recipes-mono/mono/mono-5.16.0.179/dllmap-config.in.diff
- recipes-mono/mono/mono-5.16.0.179/shm_open-test-crosscompile.diff
- recipes-mono/mono/mono-native_5.16.0.179.bb
- recipes-mono/mono/mono_5.16.0.179.bb
Just a test.
It certainly fails to build as is on Yocto 2.5 when building for genericx86 (32-bit) on x86_64.
The CMake build system has changes in this Mono version so some parts are built with the native compiler.
> Mono 5.16.0.179 support

- classes/mono.bbclass
Set NUGET_PACKAGES and NUGET_HTTP_CACHE_PATH instead of HOME.
Overriding the HOME environment variable clashes with RPM signing.
Signed-off-by: Böszörményi Zoltán <zboszor@pr.hu>
> classes/mono.bbclass: Don't override HOME

- recipes-mono/mono/mono-5.20.1.34/dllmap-config.in.diff
- recipes-mono/mono/mono_5.20.1.34.bb
After reviewing generated contents of /etc/mono/config, fixes for
the following library files are needed because they were referenced
through their SDK symlinks (which are not installed on production
systems) as opposed to the library SONAME:
* libxslt.so -> libxslt.so.1 (libxslt 1.x.y)
* libodbc.so -> libodbc.so.2 (unixODBC 2.x.y)
* libmono-native.so -> libmono-native.so.0
Signed-off-by: Böszörményi Zoltán <zboszor@pr.hu>
> Fix dllmap config for Mono 5.20.1.34

- conf/layer.conf
- recipes-mono/mono-helloworld/mono-helloworld.inc
- recipes-mono/mono/mono-5.xx.inc
Hey there,
we tried to build mono using the latest zeus version of poky. This revealed several QA issues that will be fixed with this patches. Also python is used instead of perl for some task now. This will be also added.
```
$ bitbake mono
Parsing recipes: 100% |##############################################################################################################################################| Time: 0:00:40
Parsing of 1649 .bb files complete (0 cached, 1649 parsed). 2371 targets, 67 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
Build Configuration:
BB_VERSION           = "1.44.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "x86_64-poky-linux"
MACHINE              = "qemux86-64"
DISTRO …
```
> Zeus fixes

- recipes-mono/mono/mono-5.xx.inc
- recipes-mono/mono/mono-6.xx.inc
Poky is in the middle of switching from python 2 to python 3. Python 2 is no longer available in poky master. Therefor mono 5 will no longer build.
To enable building mono 5 and 6 these changes are required.
> Python3 switch

- recipes-mono/mono/mono-5.xx.inc
- recipes-mono/mono/mono-5.xx/0003-mono-use-python3-instead-of-python.patch
- recipes-mono/mono/mono-6.xx.inc
- recipes-mono/mono/mono-6.xx/0003-mono-use-python3-instead-of-python.patch
This might be not a nice and complete approach, but building mono and mono-native in version 5 and 6 works with poky master and openembedded master.
```
$ bitbake mono
Loading cache: 100% |###################################################################################################| Time: 0:00:00
Loaded 2416 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies
Build Configuration:
BB_VERSION           = "1.44.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "x86_64-poky-linux"
MACHINE              = "qemux86-64"
DISTRO               = "poky"
DISTRO_VERSION       = "3.0+snapshot-20200207"
TUNE_FEATURES        = "m64 core2"
TARGET_FPU           = ""
meta
meta-poky
meta-yocto-bsp       = …
```
> Python3 fixes and minor mono-6.xx.inc fix

- recipes-mono/mono/mono-6.xx.inc
- recipes-mono/mono/mono_6.8.0.96.bb
Mono is expecting /usr/lib/libmono-native.so but this
was being packaged in mono-dev. When we package in the
mono-libs package we get a QA error as symlinks should
be in mono-dev.
I've not been able to change the build to require a
different library name, as this breaks mono-native
build so for now have packaged the .so symlink in
mono-libs and disabled the QA dev-so check.
Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>
> mono: Workaround libmono-native.so packaging issue

- recipes-mono/mono/mono-6.8.0.96/0001-patch-XplatUIX11-cursor.diff
- recipes-mono/mono/mono-native_6.8.0.96.bb
Issue with DefineCursor causes an exception to be thrown.
@see: https://github.com/mono/mono/issues/13049
Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>
> mono-native_6.8.0.96: Fix issue initialising Windows Form. Issue #18

- recipes-mono/mono/mono-6.xx/0003-mono-use-python3-instead-of-python.patch
Change versions.mk and versions.py in scripts/submodules to also use python
3. This is used by acceptance tests and jemalloc.
So I encountered another area where python is used in our product build. The patch just got expanded similar to the other areas.
```
$ bitbake mono
Parsing recipes: 100% |###############################################################################################################################################| Time: 0:00:44
Parsing of 1678 .bb files complete (0 cached, 1678 parsed). 2418 targets, 76 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
Build Configuration:
BB_VERSION           = "1.44.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "x86_64-poky-linux"
MACHINE …
```
> mono-6: expand python3 patch

- recipes-mono/msbuild/msbuild_15.4.bb
When used with Mono 5.20 or 6.x, projects using msbuild complain
about missing directories that previously were conflicting with
Mono.
Signed-off-by: Böszörményi Zoltán <zboszor@pr.hu>
> msbuild: Apply do_install_append() to native mode

- conf/layer.conf
Update layer compatibility list:
- remove sumo (EOL)
- add dunfell (april 2020 release)
Signed-off-by: Kraag Gorim <kraaggorim@gmail.com>
> layer.conf: update compatibility list

- recipes-mono/mono/mono-native-6.xx-base.inc
- recipes-mono/mono/mono_6.8.0.123.bb
If mono is inherited in a recipe which has BBCLASSEXTEND="nativesdk".Build will fail with error "ERROR: Nothing PROVIDES 'nativesdk-mono'". As mono is currently not providing nativesdk, This PR serves the purpose. An open issue is there with 6.10, so creating specific pull request for 6.8.0.123
> nativesdk support for mono.

- recipes-mono/libgdiplus/libgdiplus-6.xx.inc
- recipes-mono/libgdiplus/libgdiplus_6.0.2.bb
- recipes-mono/libgdiplus/libgdiplus_6.0.4.bb
Using pango as font rendering engine adds support for many alphabets/scripts in libgdiplus.
This change is only supported by libgdiplus ≥ 6.0, so I'm not sure how to handle this. I could add a version-specific `libgdiplus-6.xx.inc` file. Feedback/ideas are welcome.
> libgdiplus: Add package config for pango

- recipes-mono/mono/mono-native-6.xx-base.inc
- recipes-mono/mono/mono_6.8.0.123.bb
Upstream-Status: Backport
This is a back ported change to support on 6.8.0.123. This change will be removed once mono 6.10 upstream is fixed. 
https://github.com/mono/mono/issues/20299
> Changes for nativesdk support mono

- classes/mono.bbclass
- conf/layer.conf
- recipes-mono/dotnet/dotnet_3.1.11.bb
- recipes-mono/mono/mono-base.inc
- recipes-mono/mono/mono-native-6.xx-base.inc
- recipes-mono/msbuild/msbuild/0001-Copy-hostfxr.patch
- recipes-mono/msbuild/msbuild/0001-Don-t-try-to-run-pkill.patch
- recipes-mono/msbuild/msbuild/0002-Remove-myget-feeds-and-replace-with-AzDO-feeds.patch
- recipes-mono/msbuild/msbuild/mono-msbuild-dotnetbits-case.patch
- recipes-mono/msbuild/msbuild/mono-msbuild-license-case.patch
- recipes-mono/msbuild/msbuild/mono-msbuild-no-hostfxr.patch
- recipes-mono/msbuild/msbuild/mono-msbuild-use-bash.patch
- recipes-mono/msbuild/msbuild/mono-msbuild-use-more-bash.patch
- recipes-mono/msbuild/msbuild_16.6.bb
The current msbuild 15.4 recipe is broken. This pull request adds a new recipe for version 16.6. I was only able to test the msbuild-native recipe with mono 6.8.0.105 and poky zeus, every other configuration is completely untested.
I added a recipe for dotnet as it is a dependency of msbuild. I copied it from [intel-iot-devkit/meta-iot-cloud](https://github.com/intel-iot-devkit/meta-iot-cloud) as I didn't want to depend on the whole layer just for a single recipe. The layer is MIT licensed, this probably needs attribution.
There is also a change to use correct paths in the config for mono-native, I think this should not break other things.
It would be nice if someone can test this a bit more and give feedback.
Fixes #38.
> Add msbuild 16.6

- conf/layer.conf
The original reason for removing Yocto 2.5 Sumo support was its EOL state. But there's nothing in meta-mono that makes it
inherently incompatible with Sumo.
> conf/layer.conf: Re-enable Sumo support

- recipes-mono/libgdiplus/libgdiplus-6.xx.inc
configure.ac in libgdiplus disables detecting X11 when either
option --with-x11 or --without-x11 is present.
Don't use --with-x11 to allow detecting X11.
> libgdiplus: Don't use --with-x11 for 6.x versions

- recipes-mono/dotnet/dotnet_3.1.11.bb
- recipes-mono/msbuild/msbuild-libhostfxr/0001-Don-t-set-a-plethora-of-compiler-arguments-through-c.patch
- recipes-mono/msbuild/msbuild-libhostfxr_3.1.11.bb
- recipes-mono/msbuild/msbuild_16.6.bb
Fixes compatibility with x86 build hosts by building the library from
source and removes the dependency on the full dotnet package.
I would like to thank openSUSE for their excellent [msbuild-libhostfxr](https://build.opensuse.org/package/view_file/Mono:Factory/msbuild-libhostfxr/msbuild-libhostfxr.spec) package that put me on the right track.
Building for x86 is currently untested, if somebody has an x86 machine to test with, please do so and report back.
Fixes #64
> msbuild: Reduce dotnet dependency to libhostfxr

- recipes-mono/msbuild/msbuild-libhostfxr_3.1.11.bb
> msbuild-libhostfxr: Install libhostxfr.so into libdir in native mode

- recipes-mono/msbuild/msbuild-libhostfxr/0002-Remove-broken-objcopy-detection-STRIP_SYMBOLS-is-uns.patch
- recipes-mono/msbuild/msbuild-libhostfxr_3.1.11.bb
This is completely unnecessary since we don't set STRIP_SYMBOLS, so
objcopy is never used. The debug symbols are split later by bitbake.
This should fix the `objcopy not found` error in #65
> msbuild-libhostfxr: Patch broken objcopy detection

- recipes-mono/mono/mono-native-6.xx-base.inc
> mono: RPROVIDES needs to be package specific

- recipes-mono/msbuild/msbuild_16.6.bb
The upstream linux-packaging-msbuild repository changed their branch
name from master to main, so we need to explicitly specify it in SRC_URI
as bitbake uses master by default.
> msbuild: Match branch name to upstream

- recipes-mono/mono/mono-5.16.inc
Note this should be backported to all supported versions.
> mono: fix removing x86 binaries

- classes/mono.bbclass
If a recipe uses "inherit mono" and later writes RDEPENDS:${PN} = "..."
then RDEPENDS:${PN} += "..." in mono.bbclass will not take effect.
It's documented somewhere in the Yocto manual.
Use the override :append syntax for other variables, too, not
just RDEPENDS.
Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>
> classes/mono.bbclass: Fix ignored RDEPENDS:${PN} += "..."

- recipes-mono/nuget/nuget.inc
Maybe Microsoft didn't renew their certificate but downloading
nuget.exe fails because the cert is untrusted now.
This should only be a temporary measure.
Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>
> nuget: Set BB_CHECK_SSL_CERTS=0

- recipes-mono/msbuild/msbuild-libhostfxr_3.1.16.bb
- recipes-mono/msbuild/msbuild_16.6.bb
From the first commit:
```
Use protocol=https for git://github.com/...
GitHub will remove the unauthenticated git protocol in favour of
the (still anonymous) https protocol and they even exercised a
short brownout period.
Yocto/Bitbake started printing warnings about this.
```
> Fix SRC_URI warnings

- recipes-mono/mono/mono-git.inc
Since 11th of January I was no longer able to use the mono recipe for Sumo due to the git:// protocol being disabled:
https://github.blog/2021-09-01-improving-git-protocol-security-github/
> Change github protocol

- recipes-mono/libgdiplus/libgdiplus-6.xx.inc
- recipes-mono/libgdiplus/libgdiplus_6.0.4.bb
- recipes-mono/libgdiplus/libgdiplus_6.0.5.bb
Disabled  pango support as it breaks cursor measurement.
See; https://github.com/DynamicDevices/meta-mono/issues/105
> Disabled pango support as it breaks cursor measurement.

- recipes-mono/dotnet/dotnet_5.0.300.bb
- recipes-mono/images/test-image-mono.bb
Yocto changed the override syntax in Yocto honister (3.4). This was
introduced somehow in the dotnet recipe of the dunfell branch of
meta-mono.
Probably from https://github.com/intel-iot-devkit/meta-iot-cloud/blob/08d0c505097b889836315a4fe9b41acbb264be3f/recipes-devtools/dotnet/dotnet_5.0.300.bb
The error looks like this:
```
ERROR: ParseError at .../meta-mono/recipes-mono/dotnet/dotnet_5.0.300.bb:15: unparsed line: 'RDEPENDS:${PN} = "    icu     libgssapi-krb5     lttng-ust     zlib "'
```
Revert the changes back to the plain old Yocto override syntax.
> dotnet: Revert to old pre-honister override syntax

- .github/workflows/CI_github.yml
- recipes-mono/dotnet/dotnet_5.0.300.bb
issue #124
since dotnet 5 depends on an older version of lttng-ust, and this
dependency is not really needed for dotnet apps, remove
libcoreclrtraceptprovider.so
Signed-off-by: Ben Fekih, Hichem <hichem.f@live.de>
> dotnet 5: remove the dependency to lttng-ust

- recipes-mono/dotnet/dotnet_6.0.202.bb
`RUNTIME` variable name is too simple. For example, in Xilinx BSP somewhere there is a `RUNTIME` variable name in "global scope", so they are in conflict, therefore dotnet recipe from meta-mono layer is not parsable well. Please use more unique variable name like `DOTNET_RUNTIME` instead.
Please merge it to master, also.
> Rename RUNTIME to DOTNET_RUNTIME in dotnet_6.0.202.bb

- recipes-mono/dotnet/dotnet_6.0.302.bb
- update the dotnet6 recipes
- patch the library to not use liblttng-ust instead of deleting
it completely
- for x86 correct the interpreter path instead of creating a link
Signed-off-by: Ben Fekih, Hichem <hichem.f@live.de>
> dotnet: update to v6.0.7

- recipes-mono/mono/mono-git.inc
- recipes-mono/mono/mono-git/0001-mcs-aot-compiler-Fixes-GNU-Make-4.3-incompatibility.patch
Adds compatibility for GNU Make versions >= 4.3 which changed behaviour
around appending to empty variables
Signed-off-by: Jan Kraemer <jan.kraemer@mbition.io>
Patch Status is `pending` but we from MBition cannot contribute to mono directly. I can change it to something more appropriate if necessary.
Jan Kraemer jan.kraemer@mbition.io on behalf of MBition GmbH
https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md
> mono: Adds patch for aot-compiler Makefile

- recipes-mono/mono/mono-git.inc
- recipes-mono/mono/mono-git/0001-mcs-aot-compiler-Fixes-GNU-Make-4.3-incompatibility.patch
Adds compatibility for GNU Make versions >= 4.3 which changed behaviour
around appending to empty variables
Signed-off-by: Jan Kraemer [jan.kraemer@mbition.io](mailto:jan.kraemer@mbition.io)
Patch Status is pending but we from MBition cannot contribute to mono directly. I can change it to something more appropriate if necessary.
Jan Kraemer [jan.kraemer@mbition.io](mailto:jan.kraemer@mbition.io) on behalf of MBition GmbH
https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md
For reference, the changelog with the Make change for GNU Make 4.3:
https://lists.gnu.org/archive/html/info-gnu/2020-01/msg00004.html
> mono: Adds patch for aot-compiler Makefile Kirkstone branch

- recipes-mono/dotnet/dotnet_6.0.403.bb
- update the dotnet6 recipes to v6.0.11 and backport some further pathces from master
- patch the library to not use liblttng-ust instead of deleting it completely
- for x86 correct the interpreter path instead of creating a link
> dotnet: update to v6.0.11

- recipes-mono/msbuild/msbuild_16.6.bb
This fixes the download error and the subsequent build errors:
```
| DEBUG: Executing shell function do_compile
| ** Downloading MSBUILD from https://github.com/mono/msbuild/releases/download/0.08/mono_msbuild_6.4.0.208.zip 
| ./eng/cibuild_bootstrapped_msbuild.sh: line 59: curl: command not found 
| unzip:  cannot find or open .../msbuild-native/16.6-r0/git/eng/../artifacts/msbuild.zip,
.../msbuild-native/16.6-r0/git/eng/../artifacts/msbuild.zip.zip or
.../msbuild-native/16.6-r0/git/eng/../artifacts/msbuild.zip.ZIP.
```
> msbuild: Depend on curl-native and ca-certificates-native

- recipes-mono/mono/mono-6.12.0.161/disable-mmap-MAP_32BIT-support.patch
- recipes-mono/mono/mono-native-6.xx-base.inc
- recipes-mono/mono/mono-native_6.12.0.161.bb
- recipes-mono/mono/mono_6.12.0.161.bb
@ajlennon The patch from https://github.com/mono/mono/issues/21651#issuecomment-1539830484 fixes the segfault when building mono-native. Tested with kernel 6.3.1 on the Fedora 38 build host.
Fixes #180
> Fix mmap segfault on recent kernels

- .github/workflows/CI_github.yml
- conf/layer.conf
- recipes-mono/msbuild/msbuild-16.10.1/0001-Copy-hostfxr.patch
- recipes-mono/msbuild/msbuild-16.10.1/mono-msbuild-use-bash.patch
- recipes-mono/msbuild/msbuild_16.10.1.bb
It fixes the error in our in-house project that is really an inconsistency between the older msbuild 16.6 and the newest Mono.
> Add msbuild 16.10.1 recipe

- conf/layer.conf
- recipes-mono/gtk-sharp/gtk-sharp3_2.99.4.bb
- recipes-mono/libgdiplus/libgdiplus-common.inc
- recipes-mono/mono-addins/mono-addins-xbuild.inc
- recipes-mono/mono-addins/mono-addins.inc
- recipes-mono/mono-upnp/mono-upnp.inc
- recipes-mono/taglib-sharp/taglib-sharp.inc
This is just to get rid of warnings, not in any way a complete test, build or runtime.
> Some fixes to get Yocto 4.3 going

- classes/mono.bbclass
- recipes-mono/mono/mono-6.12.0.161.inc
- recipes-mono/mono/mono-6.xx.inc
- recipes-mono/mono/mono-base.inc
- recipes-mono/mono/mono-native-6.xx-base.inc
* mono-base: append dependencies instead of using the hard assignment op
* Remove extra space
Not needed when using the += operator.
* Fix build on aarch64 builds
When building for aarch64 targets, I get build failures like:
ERROR: msbuild-native-16.6-r0 do_prepare_recipe_sysroot: Manifest /workdir/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-mono.populate_sysroot not found in imx8mn_ddr4_evk cortexa53 armv8a-crc armv8a aarch64 allarch x86_64_x86_64-nativesdk (variant '')?
The problem comes from the fact that some include files (i.e.: mono-6.xx.inc) are used in both the mono and mono-native variants. This seems to confuse the native class in some way. Ideally we would have a single mono recipe declaring BBCLASSEXTEND = "native" and we'd let bitbake generate the recipe …
> mono: add BBCLASSEXTEND=native to mono-6.xx.inc (#149)

- recipes-mono/dotnet-helloworld/dotnet-helloworld_1.0.bb
- recipes-mono/dotnet/dotnet_8.0.101.bb
just testing if the kirkstone branch is working fine. (since this is the only version I am using right now)
> add dotnet 8 to kirkstone

- .github/workflows/CI_github.yml
- conf/layer.conf
- recipes-mono/mono-helloworld/mono-helloworld.inc
- Use Node 20 instead of Node 16
- Use `bitbake -c cleanall test-image-mono dotnet dotnet-native` only for reduce rebuild time
- Suppress TMPDIR warnings
> ci: optimize CI build

- .github/workflows/CI_github.yml
- README.md
- conf/layer.conf
- recipes-mono/dotnet-helloworld/dotnet-helloworld_1.0.bb
- recipes-mono/gtk-sharp/gtk-sharp.inc
Use scarthgap branch in CI build
> Use scarthgap branch in CI build

- .github/workflows/CI_github.yml
- conf/layer.conf
- recipes-mono/mono/mono-6.12.0.206.inc
- recipes-mono/mono/mono-6.12.0.206/0001-Allow-passing-external-mapfile-C-build-options.patch
- recipes-mono/mono/mono-6.12.0.206/0001-patch-XplatUIX11-cursor.diff
- recipes-mono/mono/mono-6.12.0.206/disable-mmap-MAP_32BIT-support.patch
- recipes-mono/mono/mono-6.12.0.206/shm_open-test-crosscompile.diff
- recipes-mono/mono/mono-native_6.12.0.206.bb
- recipes-mono/mono/mono_6.12.0.206.bb
This version was actually used to work out the reproducible build issues in styhead.
This is the last tagged version in https://github.com/mono/mono/tags before the Mono was handed to the Wine project.
See also https://www.mono-project.com/ for the announcement.
The new version was not released as a tarball, so the bootstrap procedure downloads the mini mono. This needs
```
do_compile[network] = "1"
```
for the native build.
> mono 6.12.0.206

- recipes-mono/mono/mono-4.xx.inc
It seems that at some point, the script was moved from the base package, to the `-dev` package. I haven't tested every 4.xx package, but I did try `4.0.2.4`, and the build went through fine, and I can see that this change was also made in 5.xx, so I assume all of 4.xx should have it as well.
Fixes the following error:
```
ERROR: mono-4.6.1.5-r0 do_package_qa: QA Issue: /usr/bin/mono-find-requires contained in package mono-dev requires /bin/bash, but no providers found in RDEPENDS:mono-dev? [file-rdeps]
ERROR: mono-4.6.1.5-r0 do_package_qa: Fatal QA errors were found, failing task.
```
> mono: fix RDEPENDS for mono-4.xx

- recipes-mono/mono/mono-base.inc
Closes #238 
When building for an image with multilib (for 32 bit x86), the `${libdir}` variable gets changed from `/usr/lib` to `/usr/lib64` - but `mono-native` still outputs the libraries into `/usr/lib`.
This is one approach that fixes that issue.
Note: this also should be backported as far back as Kirkstone, maybe further - I dunno what your workflow for that is.
> Fix native libdir path for multilib

- recipes-mono/mono/mono-4.xx.inc
- recipes-mono/mono/mono-4.xx/0003-include-sys-sysmacros.h-for-makedev.patch
- recipes-mono/mono/mono-base.inc
> Backport mono fixes to dunfell
